### ISSUE TITLE
Code cleanup!

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/Hacktoberfest2020#610]
# Description
The language folders have a lot of files that are not part of any subfolder. Some of them are potentially the same code with the same different approaches. I want:
- All the code files, well arranged. 
- If you can evaluate the code quality and find them poorly written, feel free to remove them. 
- Just list all the files removed so that others can contribute better code.
- Every language will be assigned to a different person for a fair chance. 

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @vikhyat-github [DONE]
-   [ ] C: @
-   [ ] C++: @

**Comment by govindraj111** [comment]
@kaustubhgupta assign this to me! Would like to contribute.

**Comment by VishalS047** [comment]
Hey assign this to me I would like to contribute

**Comment by vikhyat-github** [comment]
@kaustubhgupta I would like to contribute in Java

**Comment by theyashwanthsai** [comment]
hey, i can contribute to this. would love to contribute

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I would like to contribute to Java

Assigned to you in Java

**Comment by kaustubhgupta** [comment]
@govindraj111 @VishalS047 @theyashwanthsai let me know your preferred languages

**Comment by vikhyat-github** [comment]
@kaustubhgupta 
Can you please elaborate on the description about what exactly you want.
What do you mean by well arranged? Do I have to write code myself also or just remove unnecessary code or correct it?
please elaborate more so that we can be more efficient.
I hope you understand.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta Can you please elaborate on the description about what exactly you want. What do you mean by well-arranged? Do I have to write code myself also or just remove unnecessary code or correct it? please elaborate more so that we can be more efficient. I hope you understand.

For example, you can create subfolders under the Java directory for Sorting Algos where all the sorting algorithms such as heap sort, merge are present. In this way, you can create multiple subfolders for such categories. If you don't find any particular category, then put in Others. 

And, do check if the codes are good enough and not repetitive. You can free to remove such cases.

**Comment by vikhyat-github** [comment]
ok great thanks

**Comment by theyashwanthsai** [comment]
@kaustubhgupta java

**Comment by govindraj111** [comment]
@kaustubhgupta Will be drilling it with Java !

**Comment by kaustubhgupta** [comment]
Java is already assigned, you can pick up other languages

**Comment by VishalS047** [comment]
I would like to work on java

**Comment by vikhyat-github** [comment]
@kaustubhgupta 
I have made a PR please review it.
I am waiting for your acceptance.
