### ISSUE TITLE
C++/fah_to_cel_function(CB).cpp [Required output not received]

### ISSUE THREAD

**Issue by arpitbaheti2002** [kaustubhgupta/Hacktoberfest2020#622]
The datatype of c (Celcius) in C++/fah_to_cel_function(CB).cpp has int datatype. So the output is rounded to the lower integer which for most of the cases is giving incorrect output.

**Comment by arpitbaheti2002** [comment]
Hello, sorry for bothering you but I am a beginner and having difficulty to understand what is the Error IN Template tag is for. Can you please explain it to me?

**Comment by kaustubhgupta** [comment]
You can look at this issue template: https://github.com/kaustubhgupta/Hacktoberfest/issues/623

**Comment by arpitbaheti2002** [comment]
> You can look at this issue template: #623

That is really good insight for explaining issues. I will try editing my description of this issue. Thank you

**Comment by kaustubhgupta** [comment]
> > You can look at this issue template: #623
> 
> That is really good insight for explaining issues. I will try editing my description of this issue. Thank you

You can edit the other issue template, the python one, as I am merging the PR for this issue

**Comment by arpitbaheti2002** [comment]
Thank you very much.
