### ISSUE TITLE
Key Pad Problem [Asked in FAANG Interview]

### ISSUE THREAD

**Issue by ankit-95** [kaustubhgupta/Hacktoberfest2020#623]
# Description
I want to add Key Pad Problem Code in Java that was asked in one of my interviews.
  
# Additional context
Similar to Letter Combinations of a Phone Number Problem on Leetcode [https://leetcode.com/problems/letter-combinations-of-a-phone-number/] 

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @ankit-95 
-   [ ] C: @
-   [x] C++: @Exynos03 

# Notes
I have read the CODE_OF_CONDUCT.md and CONTRIBUTING.md. Please assign the issue to me.

**Comment by ankit-95** [comment]
@kaustubhgupta. Please assign this issue to me.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta. Please assign this issue to me.

Sure, go ahead with the implementation

**Comment by ankit-95** [comment]
@kaustubhgupta : I have created the pull Request #625 which will close this issue

**Comment by NavanshGoel** [comment]
@kaustubhgupta Could I provide a solution for this problem in Python?

**Comment by ankit-95** [comment]
Closes #625

**Comment by ankit-95** [comment]
https://github.com/kaustubhgupta/Hacktoberfest/pull/625

**Comment by Exynos03** [comment]
@kaustubhgupta Please assign me this issue. i will solve it in c++

**Comment by hackgone** [comment]
i can solve this with java

**Comment by kaustubhgupta** [comment]
@hackgone already implemented in java, choose another language

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta Please assign me this issue. i will solve it in c++

done
