### ISSUE TITLE
Trapping Rain Water problem

### ISSUE THREAD

**Issue by ayush-t02** [kaustubhgupta/Hacktoberfest2020#626]
# Description
(Replace this text holder with your description: Please include a small description or summary of the issue here )

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [ ] I have read the contribution guidelines before making this issue.
-   [ ] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @
-   [ ] C: @
-   [ ] C++: @ 

# Notes
Anything you would like to discuss.

**Comment by VishalS047** [comment]
please assign me this issue (JAVA)

**Comment by ng29** [comment]
can i pick this up for c++?
