### ISSUE TITLE
Shortest knight path

### ISSUE THREAD

**Issue by aastha0326** [kaustubhgupta/Hacktoberfest2020#632]
# Description
Given a square chessboard of N x N size, the position of Knight and position of a target is given, the task is to find out the minimum steps a Knight will take to reach the target position-This a classic DP problem.

# Important Checklist 
-   [ ] I have read the contribution guidelines before making this issue.
-   [ ] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [ ] Python: @
-   [ ] Java: @

**Comment by aastha01chauhan** [comment]
Please add hacktober fest tag here.

**Comment by Prakhar-creator** [comment]
Hello,@aastha01chauhan ma'am, I am a college student from CSE Dept, open source contribution is very important aspect to develop and enhance my problem solving skills. Can I contribute to this open source problem, it will be very helpful from my career Aspects and also a better learning experience in Hacktoberfest 2021.
