### ISSUE TITLE
Two Sum Problem in O(nlog(n))

### ISSUE THREAD

**Issue by divya-rai-42** [kaustubhgupta/Hacktoberfest2020#634]
# Description
Given an array and a particular number as a target , the aim is two find whether there exist two numbers in the array such that their sum is equal to the given target.
Eg: array-> 1 -5 7 9 4 6
      target-> 8
      Output: Yes

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [X] Python: @aastha01chauhan 
-   [x] Java: @susheel-kumar-1998 
-   [x] C: @laxmipandey47
-   [x] C++: @divya-rai-42 

# Notes
NA

**Comment by divya-rai-42** [comment]
@kaustubhgupta  please assign this issue to me if you find it worth.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta please assign this issue to me if you find it worth.

Sure, go ahead with the implementation

**Comment by susheel-kumar-1998** [comment]
Hi, I would like to solve this problem in O(n) complexity. please, assign this issue to me. my code of preference would be java.

**Comment by kaustubhgupta** [comment]
> Hi, I would like to solve this problem in O(n) complexity. please, assign this issue to me. my code of preference would be java.

sure

**Comment by laxmipandey47** [comment]
@kaustubhgupta I want to contribute in C language, please assign.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I want to contribute in C language, please assign.

done

**Comment by aastha0326** [comment]
I want to contribute in python, please assign this issue to me.

**Comment by Exynos03** [comment]
I want to solve this problem in java. Please assign me this issue.

**Comment by PrabhuRaamDev** [comment]
I want to contribute in java. Please assign to me

**Comment by kaustubhgupta** [comment]
> I want to contribute in python, please assign this issue to me.

done
