### ISSUE TITLE
Shell Sort algorithm

### ISSUE THREAD

**Issue by Sam071100** [kaustubhgupta/Hacktoberfest2020#637]
# Description
Adding the code of Shell sort algorithm

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [ ] Python: @
-   [ ] Java: @
-   [ ] C: @
-   [x] C++: @Sam071100 

# Notes
Anything you would like to discuss. 
Shell sort, also known as Shell sort or Shell's method, is an in-place comparison sort. It can be seen as either a generalization of sorting by exchange (bubble sort) or sorting by insertion (insertion sort).

**Comment by vinitvins** [comment]
Can you add hacktoberfest label

**Comment by Sam071100** [comment]
> Can you add hacktoberfest label

Adding labels is not in my hands as I was not able to add the labels. If you can please add or please guide me to do so. Labels are managed by Github actions and moreover I think github actions is not working properly as for all the other issues made after me have been allotted the same tags as this issue got.
