### ISSUE TITLE
First Common Ancestor

### ISSUE THREAD

**Issue by AtalKhandelwal** [kaustubhgupta/Hacktoberfest2020#646]
# Description
I want to add a program to find First Common Ancestor in a Binary Tree

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [ ] Python: @
-   [x] Java: @AtalKhandelwal 
-   [ ] C: @
-   [ ] C++: @ 

# Notes
Anything you would like to discuss.

**Comment by AtalKhandelwal** [comment]
@kaustubhgupta I would like to contribute for this issue in java.

**Comment by kaustubhgupta** [comment]
> @kaustubhgupta I would like to contribute for this issue in java.

sure
