### ISSUE TITLE
K Largest element in array using heap

### ISSUE THREAD

**Issue by Priya272** [kaustubhgupta/Hacktoberfest2020#649]
Find all the k largest elements are present in an array/vector. It will use heap data structure for solving.

example:-
arr=[1,2,3,4,5,6] and k=3
then the output will be:
[4,5,6] which are the 3 largest elements present in the array.

# Languages and Assignees:
-   [x] Python: @aastha01chauhan 
-   [x] Java: @PrabhuRaamDev 
-   [ ] C: @
-   [x] C++: @Priya272  

# Notes
This code will be helpful as it will help us to find the range of all greater no present in an array.

**Comment by Priya272** [comment]
@kaustubhgupta  please assign this issue to me!

**Comment by aastha0326** [comment]
Please assign this issue to me in java and/or python

**Comment by PrabhuRaamDev** [comment]
I would like to contribute in java.Kindly please assign me

**Comment by kaustubhgupta** [comment]
@aastha01chauhan @PrabhuRaamDev Pls check your language assignments
