### ISSUE TITLE
Tower of Hanoi : A mathematical puzzle [Asked in FAANG Interview]

### ISSUE THREAD

**Issue by ankit-95** [kaustubhgupta/Hacktoberfest2020#652]
# Description
This Problem requires you to move disks from Stand A to Stand C where Stand B is a helper.
Stand A contains some disks as which are required to be moved to Destination C.

# Additional context
Tower of Hanoi is a mathematical puzzle where we have three rods and n disks.
    The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules:
    1. Only one disk can be moved at a time.
    2. Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack.
    3. No disk may be placed on top of a smaller disk.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [x] Python: @aastha01chauhan 
-   [x] Java: @ankit-95
-   [ ] C: @
-   [x] C++: @ShreyaDayma-cse 

# Notes
I have read the CODE_OF_CONDUCT.md and CONTRIBUTING.md. Please assign the issue to me.

**Comment by ankit-95** [comment]
@kaustubhgupta. Please assign this issue to me.

**Comment by hackgone** [comment]
can i work on it?

**Comment by ShreyaDayma-cse** [comment]
I would like to contribute in this

**Comment by kaustubhgupta** [comment]
@hackgone @ShreyaDayma-cse language?

**Comment by hackgone** [comment]
Java

**Comment by kaustubhgupta** [comment]
> Java

Choose languages that are not taken by anybody else

**Comment by ShreyaDayma-cse** [comment]
> @hackgone @ShreyaDayma-cse language?

Java

**Comment by aastha0326** [comment]
please assign this to me in  python

**Comment by ShreyaDayma-cse** [comment]
I will do it in C++

**Comment by ankit-95** [comment]
@kaustubhgupta : I have created the pull Request #669 which will close this issue for Java.

**Comment by kaustubhgupta** [comment]
> I will do it in C++

done
