### ISSUE TITLE
Sort linked list using Merge Sort

### ISSUE THREAD

**Issue by divya-rai-42** [kaustubhgupta/Hacktoberfest2020#656]
# Description
Given a linked list, sort it using the merge sort algorithm.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [x] Python: @saketmundra 
-   [x] Java: @PrabhuRaamDev 
-   [ ] C: @
-   [x] C++: @divya-rai-42 

# Notes
Anything you would like to discuss.

**Comment by divya-rai-42** [comment]
@kaustubhgupta I would like to contribute this in C++. Please assign it to me

**Comment by PrabhuRaamDev** [comment]
I want to contribute in java.Kindly please assign me

**Comment by saketmundra** [comment]
I want to contribute this in python. Please assign me.

**Comment by kaustubhgupta** [comment]
> I want to contribute this in python. Please assign me.

Done
