### ISSUE TITLE
All about Singly Linked List

### ISSUE THREAD

**Issue by prachi610** [kaustubhgupta/Hacktoberfest2020#659]
# Description
Java code for implementation Singly Linked List. Creation of SLL, Insertion, and Deletion from the front, back, and from a given index, printing the element present at the given index, printing list in forward and reverse order.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [x] Python: @aastha01chauhan 
-   [x] Java: @prachi610
-   [ ] C: @
-   [ ] C++: @

**Comment by aastha0326** [comment]
please assign this to me in  python

**Comment by prachi610** [comment]
@kaustubhgupta Thank you!

**Comment by manish866** [comment]
Please assign me I will do it in java

**Comment by kaustubhgupta** [comment]
> Please assign me I will do it in java

Java implementation was already taken up, choose another language
