### ISSUE TITLE
Grid Travel Problem 

### ISSUE THREAD

**Issue by Maulikchhabra** [kaustubhgupta/Hacktoberfest2020#661]
# Description
I want to add this problem where we can travel in a matrix or grid and get the total number of ways to travel.

# Additional context
Add any other context, links references or screenshots about the feature request here.

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented

# Languages and Assignees:
-   [x] Python: @aastha01chauhan
-   [x] Java: @Maulikchhabra
-   [ ] C: @
-   [ ] C++: @ 

# Notes
Anything you would like to discuss.

**Comment by aastha0326** [comment]
please assign this to me in java and/or python

**Comment by Maulikchhabra** [comment]
Link to the PR: #667 
@kaustubhgupta

**Comment by kaustubhgupta** [comment]
> please assign this to me in java and/or python

Python
